### ISSUE TITLE
MSI GT72-Dominator PRO Error: cannot open device with vendor id 0x1770 and product id 0xff00

### ISSUE THREAD

**Issue by thefabulousdev** [wearefractal/msi-keyboard#29]
When trying to run 

```js
var keyboard = require('msi-keyboard');

keyboard.color('left', {
	color: 'red',
	intensity: 'med'
});
keyboard.color('middle', {
	color: 'green',
	intensity: 'med'
});
keyboard.color('right', {
	color: 'blue',
	intensity: 'med',
});

keyboard.mode('breathe');

keyboard.blink(['left'], 750);

setTimeout(keyboard.stopBlink, 5000);

```

The following error is shown

``` 
	this._raw = new (Function.prototype.bind.apply(binding.HID,
	            ^

Error: cannot open device with vendor id 0x1770 and product id 0xff00
    at Error (native)
    at new HID (/home/joel/Documents/Personal/msi-klm/node_modules/msi-keyboard/node_modules/node-hid/nodehid.js:28:14)
    at module.exports (/home/joel/Documents/Personal/msi-klm/node_modules/msi-keyboard/lib/findKeyboard.js:7:14)
    at Object.<anonymous> (/home/joel/Documents/Personal/msi-klm/node_modules/msi-keyboard/index.js:3:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

```

**Comment by stevelacy** [comment]
use sudo
